#spring:
#    rabbitmq:
#        host: 192.168.1.202
#        port: 5672
#        username: test
#        password: test
# Single file max size
multipart.maxFileSize: 100Mb
# All files max size
multipart.maxRequestSize: 1000Mb

#spring.http.multipart.local:
# pagehelper
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

